# Generated by Django 4.2.25 on 2025-10-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
